### ISSUE TITLE
"$exact" type release?

### ISSUE THREAD

**Issue by denkigai** [PassFort/json-schema-to-flow-type#23]
Hi, I appreciate your great work!

it seems that you have already pushed new feature for "$exact" type [here](https://github.com/PassFort/json-schema-to-flow-type/commit/dc354c020b7a08768f61f59e908520d0fdedc02e), so i want to know when you will publish it on npm.

I'd love to use it soon!

**Comment by wmonk** [comment]
Hey all published in `0.3.0` - enjoy!
